export const SUGGESTION_LIST_API_URL = process.env.REACT_APP_SUGGESTION_LIST_API_URL;

export const GET_SUGGESTION_LIST = 'GET_SUGGESTION_LIST';

export const CLEAR_SUGGESTION_LIST = 'CLEAR_SUGGESTION_LIST';
